# Generated by Django 6.0.4 on 2026-04-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='producersuborder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
